[package]
name = "wallet_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
bip329 = "0.1.1"
miniscript = { version = "12.3.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
